spring.application.name=poke-dex-plus-backend
server.port=${PORT}
spring.main.lazy-initialization=true

# Database configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Actuator configuration -> status
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Logging settings in the application
logging.level.org.springframework.web=debug
logging.level.org.springframework.boot.actuate=info
#logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Data
jwt.key=${JWT_KEY}
