# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/poke-dex-plus?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true

# Data
jwt.secret=thisIsMysecregtfrdesww233eggtfrdesww233